# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DioThirdFinalChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'DioBootcampNetwork/Debug', :path => '/Users/giusevero/Documents/DioBootcamp/DioFinalChallenge/DioBootcampNetwork'
  pod 'lottie-ios'
  pod 'SDWebImage', '~> 5.0'
  
end
